###############################################################################
#
#   Config options for the snakemake workflow
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 15-02-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---

### WORKFLOW PARAMETERS ###

# Path to the cloned repository
# (absolute path is required)
workflow_repo_path: ""

# Path for the output directory
# (absolute path is required)
workflow_analysis_outdir: ""

### DEMON PARAMETERS ###

# spatial_structure
demon_log2_deme_carrying_capacity:

# dispersal
demon_migration_type:
demon_init_migration_rate:
demon_migration_edge_only:
demon_migration_rate_scales_with_K:

# mutation_rates
demon_mu_driver_birth:
demon_mu_passenger:
demon_mu_driver_migration:
demon_passenger_pop_threshold:
  
# fitness_effects
demon_normal_birth_rate:
demon_baseline_death_rate:
demon_s_driver_birth:
demon_s_passenger:
demon_s_driver_migration:
demon_max_relative_birth_rate:
demon_max_relative_migration_rate:

# non_biological_parameters
demon_init_pop:
demon_matrix_max:
demon_max_pop:
demon_max_time:
demon_max_generations:
demon_seed:
demon_write_grid:
demon_write_clones_file:
demon_write_demes_file:
demon_record_matrix:
demon_write_phylo:
demon_calculate_total_diversity:
demon_biopsy_size_per_sample:

...
