###############################################################################
#
#   Software to be installed in the main environment
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 08-05-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---

  name: demon-runner

  channels:
    - bioconda
    - conda-forge

  dependencies:
    - boost-cpp=1.74.0
    - compilers=1.4.2
    - graphviz=2.42.3
    - jinja2=3.1.2
    - python=3.8.0
    - pyyaml=6.0
    #- r-base=4.0.3
    #- r-devtools=2.4.3
    #- rpy2=3.5.1
    - snakemake=7.6.1

...
